# Generated by Django 4.2.7 on 2023-11-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_ID', models.IntegerField()),
                ('employee_joined_date', models.DateField()),
                ('employee_monthly_salary', models.IntegerField()),
                ('employee_adress', models.CharField(max_length=255)),
                ('employee_designation', models.CharField(max_length=20)),
            ],
        ),
    ]
